CREATE TABLE `training_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`contactPerson` varchar(255) NOT NULL,
	`address` text NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320) NOT NULL,
	`machineBrand` varchar(255),
	`machineModel` varchar(255),
	`oemName` varchar(255),
	`oemAddress` text,
	`oemContact` varchar(255),
	`oemEmail` varchar(320),
	`oemPhone` varchar(50),
	`controllerModel` varchar(255),
	`machineType` varchar(100),
	`programmingType` varchar(100),
	`trainingDays` int,
	`trainees` int,
	`knowledgeLevel` varchar(100),
	`applicantName` varchar(255),
	`applicationDate` timestamp,
	`signatureData` text,
	`termsAccepted` boolean NOT NULL DEFAULT false,
	`trainingPrice` int,
	`travelTime` int,
	`travelExpenses` int,
	`totalPrice` int,
	`language` varchar(10) DEFAULT 'en',
	`status` enum('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `training_requests_id` PRIMARY KEY(`id`)
);
